"""liabilities goals snapshots

Revision ID: 0005_liabilities_goals_snapshots
Revises: 0004_prices_lots
Create Date: 2026-06-20
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005_liabilities_goals_snapshots'
down_revision: Union[str, None] = '0004_prices_lots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('target_net_worth', 'target_return', 'target_allocation', 'custom', name='goal_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('target_allocation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'achieved', 'archived', name='goal_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_user_id'), 'goal', ['user_id'], unique=False)
    op.create_table('liability',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('loan', 'mortgage', 'installment', 'credit', 'other', name='liability_type'), nullable=False),
    sa.Column('principal', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('schedule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_user_id'), 'liability', ['user_id'], unique=False)
    op.create_table('portfolio_snapshot',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('total_assets_irr', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('total_assets_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('total_liabilities_irr', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('total_liabilities_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('net_worth_irr', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('net_worth_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'as_of', name='uq_snapshot_user_as_of')
    )
    op.create_index(op.f('ix_portfolio_snapshot_as_of'), 'portfolio_snapshot', ['as_of'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshot_user_id'), 'portfolio_snapshot', ['user_id'], unique=False)
    op.create_table('liability_event',
    sa.Column('liability_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('disbursement', 'repayment', 'interest', name='liability_event_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('interest_component', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['liability_id'], ['liability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_event_liability_id'), 'liability_event', ['liability_id'], unique=False)
    op.create_index(op.f('ix_liability_event_occurred_at'), 'liability_event', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liability_event_occurred_at'), table_name='liability_event')
    op.drop_index(op.f('ix_liability_event_liability_id'), table_name='liability_event')
    op.drop_table('liability_event')
    op.drop_index(op.f('ix_portfolio_snapshot_user_id'), table_name='portfolio_snapshot')
    op.drop_index(op.f('ix_portfolio_snapshot_as_of'), table_name='portfolio_snapshot')
    op.drop_table('portfolio_snapshot')
    op.drop_index(op.f('ix_liability_user_id'), table_name='liability')
    op.drop_table('liability')
    op.drop_index(op.f('ix_goal_user_id'), table_name='goal')
    op.drop_table('goal')
    # named enum types are not auto-dropped with their tables
    op.execute('DROP TYPE IF EXISTS liability_event_type')
    op.execute('DROP TYPE IF EXISTS liability_type')
    op.execute('DROP TYPE IF EXISTS goal_status')
    op.execute('DROP TYPE IF EXISTS goal_type')
    # ### end Alembic commands ###
