"""assumptions and inflation

Revision ID: 0006_assumptions_and_inflation
Revises: 0005_liabilities_goals_snapshots
Create Date: 2026-06-20
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0006_assumptions_and_inflation'
down_revision: Union[str, None] = '0005_liabilities_goals_snapshots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_currency', sa.Enum('irr', 'usd', 'both', name='display_currency'), nullable=False),
    sa.Column('hurdle_mode', sa.Enum('fixed', 'inflation', 'usd_growth', name='hurdle_mode'), nullable=False),
    sa.Column('hurdle_fixed_rate', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('growth_assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_user_id'), 'assumptions', ['user_id'], unique=True)
    op.create_table('inflation_rate',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_year', 'period_month', name='uq_inflation_user_period')
    )
    op.create_index(op.f('ix_inflation_rate_user_id'), 'inflation_rate', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inflation_rate_user_id'), table_name='inflation_rate')
    op.drop_table('inflation_rate')
    op.drop_index(op.f('ix_assumptions_user_id'), table_name='assumptions')
    op.drop_table('assumptions')
    # named enum types are not auto-dropped with their tables
    op.execute('DROP TYPE IF EXISTS hurdle_mode')
    op.execute('DROP TYPE IF EXISTS display_currency')
    # ### end Alembic commands ###
